### ISSUE TITLE
Which dependencies are used?

### ISSUE THREAD

**Issue by sebastianroming** [thankthemaker/sharespresso#20]
When trying to build the project in PlatformIO, i get a lot of dependency errors, like...

```
src\IMessageBroker.h:7:16: fatal error: FP.h: No such file or directory

************************************************************
* Looking for FP.h dependency? Check our library registry!
*
* CLI  > platformio lib search "header:FP.h"
* Web  > https://platformio.org/lib/search?query=header:FP.h
*
************************************************************
```

Which dependencies are used here? There are plenty of `FP` search results in the registry...

btw: the missing `FP` dependency is just an example for all the missing ones.

**Comment by thankthemaker** [comment]
Hi Sebastian,
yes, you're right. We're missing some kind of documentation regarding the dependencies.
I'll catch up on that later, for the moment I share the libraries I used globally in my

- Adafruit GFX Library by Adafruit, Ver. 1.2.9
- Adafruit PN532 by Adafruit, Ver. 1.0.2
- Adafruit ST7735 and ST7789 Library by Adafruit, Ver. 1.2.2
- ArduinoJson-esphomelib by Benoit Blanchon, Ver. 5.13.3
- ESP32httpUpdate by Matej Sychra, Ver. 2.1.145
- IFTTTWebhook by John Romkey, Ver. 1.1.2
- MFRC522 by Miguel Balboa, Ver. 1.3.6
- Paho by Eclipse, Ver. 1.0.0
- Time by Michael Margolis, Ver. 1.5
- U8g2 by oliver, Ver. 2.23.18

I hope this helps you making the code compile.
David

**Comment by sebastianroming** [comment]
Thanks a lot, that helps for a while. And yep, build documentation is missing, also for the Ionic app ;-) But I'll catch through...

**Comment by thankthemaker** [comment]
Updated and moved the Readme.md
