### ISSUE TITLE
Wrong board configuration -> wrong includes?

### ISSUE THREAD

**Issue by sebastianroming** [thankthemaker/sharespresso#23]
In your blog entry you wrote about the Sparkfun ESP8266, but due to lack of flash storage, you decided to use the NodeMCU. 

I ordered the hardware just as described [here in the blog](http://www.thank-the-maker.org/posts/paymentsystemhardware1/), but I saw that your PlatformIO configuration matches for the SparkFun board. (e.g. `WiFiMulti.h` dependency in the `wifi.h` file.)

I'm a bit confused... could you clarify? ☺️ 

Thanks a lot!

**Comment by thankthemaker** [comment]
Hi Sebastian,
we changed the hardware setup multiple times. That's the reason why we use multiple libraries and have multiple implementations for Display, CardReader, MCU, ...
The libraries you'll need and the settings depend on the hardware setup you choose. There's nothing wrong about the NodeMCU 8266 or NodeMCU ESP32, you could use either of them. 
In our company we switched to the Sparkfun ESP32 a few weeks ago. The main reason for the switch from 8266 to ESP32 is the implementation of new features, which require some additional IO-Ports and some other features of the ESP32, e.g. Touch.  
I'll also write aanother blog post as soon as I have some spare time.

**Comment by sebastianroming** [comment]
Thanks for the update on this, maybe I should consider that too then ;-) 

But after changing the configuration from Sparkfun ESP32 to NodeMCU 8266, the `WifiMulti.h` dependency is not found anymore and the project build fails. So: which library do you recommend for the use with NodeMCU to get the correct dependency?

**Comment by thankthemaker** [comment]
Ok, that seems to be an issue. I didn't try to build for the 8266 after migrating to ESP32.
I'll try to investigate this in the afternoon

**Comment by sebastianroming** [comment]
Great, thanks. Let me know if you've found out what's wrong (I'm sorry, I'm not really into C++... :smirk:)

**Comment by thankthemaker** [comment]
Hi Sebastian,
I committed some changes that should fix building issues. Please notice, I also changed platformio.ini to exclude some libs for NodeMCU 8266 build which won't work. That may conflict with your own platformio.ini.
I hope your build will now succeed.

**Comment by sebastianroming** [comment]
Thanks a lot. The code seems to compile now, let's see if it works :-)
